---
- hosts: webservers
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: install apache2
      apt: name={{item}} state=present update_cache=no
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
         
