- name: ec2 launcher
  hosts: webservers
  user: ansible
  connection: ssh
  tasks:
  - name: launching ec2
    ec2:
      instance_type: t2.micro
      key_name: ubucli
      image: ami-0cd3dfa4e37921605
      region: us-east-2
      group: default
      count: 1
      vpc_subnet_id: subnet-04a36948
      wait: yes
      assign_public_ip: yes
