---
- hosts: webservers
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=no
      
    - name: ensure nginx started
      service: name=nginx state=started enabled=yes 
