- hosts: webservers
  user: ansible
  sudo: yes 
  connection: ssh 
  gather_facts:  no 
  tasks:
  - name: repos enabled
    apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' state=present update_cache=no
  - name: add VirtualBox repo signing key
    apt_key: state=present  url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
  - name: add key
  action: command wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | apt-key add -
    sudo: yes
  - name: software installed
    apt: pkg=virtualbox-4.3 state=present update_cache=yes
