---
- hosts: webservers
  user: ansible
  connection: ssh
  tasks:
   - name: Install base packages
     apt: name={{ item }} state=present update_cache=no
     with_items:
       - locales
       - build-essential
       - acl
       - ntp
       - htop
       - git
       - supervisor
       - python-pip
       - python3-pip
       - nginx
     tags:
       - packages
   - name: Upgrade pip
     pip: name=pip state=latest
     tags:
       - packages
   - name: Create user
     user:
       name: "deploy_user"
       comment: "Used to deploy Django"
       state: present
   - name: Create .ssh folder
     file:
       path: "/home/deploy_user/.ssh/"
       state: directory
       mode: 0755    
